import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className="text-2xl m-10 ">Upgrade your ReactJS skills today</h2>
        <h3 className="text-l ml-10" >Learn web development using the latest technology.</h3>
      </main>
    </div>
  );
}
